language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xiaobin-zhang"
  - git config user.email "18235442561@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${git_blog_token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/xiaobin-zhang/xiaobin-zhang.github.io.git